version: '2'

services:
  traefik:
    image: traefik
    container_name: drupalproxy
    restart: unless-stopped
    #command: -c /dev/null --web --docker --logLevel=DEBUG
    command: -c /dev/null --web --docker --logLevel=DEBUG --defaultEntryPoints='https' --entryPoints="Name:https Address::443 TLS:/certs/imaginelearning.com.cert,/certs/imaginelearning.com.key" --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"
    networks:
      - project1
      - project2
      - project3
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs/ 

networks:
  project1:
    external:
      name: corporate_default
  project2:
    external:
      name: university_default
  project3:
    external:
      name: support_default
